before_install: git submodule update --init
script: "make test"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "irc.suikawiki.org#mechanize"
    use_notice: true
env:
  global:
    secure: 
after_success:
  - curl https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
